### ISSUE TITLE
Missing module in requirements_dev.txt

### ISSUE THREAD

**Issue by toyg** [tonybaloney/pyucwa#1]
In order to successfully start `ucwa.http`, you need the `future` module, which is missing in `requirements_dev.txt`. Because the PyPI package of that module seems broken (it failed to install on my OSX Python 2.7.11), I even had to get the upstream repository, so I suggest the actual line to add in requirements.txt for the time being should be:

`-e git+https://github.com/PythonCharmers/python-future#egg=future`

**Comment by tonybaloney** [comment]
Done. thanks for the heads up. I'm sure future should be bundled with most installs these days?

**Comment by toyg** [comment]
Thanks for the fix. It helps being explicit -- any time I try a new lib, i create an empty virtualenv, which is why I hit this.
