### ISSUE TITLE
URLS in CONTRIBUTING.rst are wrong

### ISSUE THREAD

**Issue by toyg** [tonybaloney/pyucwa#2]
They refer to /ucwa/ , clearly the old repository name.

(BTW, the old ucwa module in PyPI should be pulled if it's obsolete, it's full of these old urls.)

**Comment by tonybaloney** [comment]
Oops, that was the slug. The package is called ucwa, the PyPI package likewise. My git repo name is just pyucwa. You can pull and download ucwa from PyPI

**Comment by tonybaloney** [comment]
done.

**Comment by toyg** [comment]
Sorry for being pedantic -- you want to fix it in setup.py as well :) otherwise in PyPI you get "Home Page: https://github.com/tonybaloney/ucwa" which goes 404.
