### ISSUE TITLE
Autodiscovery must deal with "redirect"

### ISSUE THREAD

**Issue by toyg** [tonybaloney/pyucwa#3]
For the domain I'm working with (`infratects.com`), the first autodiscovery request does not actually include the `user` resource, but rather a `redirect` one; only by going to *that* url you get an actual `user` dict.

Hence, the bulk of `do_autodiscovery()` in ucwa/actions.py should look something like this:

```
    discovery = r.json()
    path = None
    if discovery['_links'].get('user', False):
        path = discovery['_links']['user']['href']
    elif discovery['_links'].get('redirect', False):
        tmp_redir = requests.get(discovery['_links']['redirect']['href'])
        discovery_redir = tmp_redir.json()
        if discovery_redir['_links'].get('user', False):
            path = discovery_redir['_links']['user']['href']
        else:
            raise Exception("Could not make sense of these links: " + tmp_redir.content)
    domain = urlparse(path)
   ...
```

**Comment by tonybaloney** [comment]
Is this on prem SfB 2016? I've only tested this library against O365. I reviewed some of the concepts with a SfB architect and there are probably a few changes to make. Happy to take all feedback and update the package

**Comment by tonybaloney** [comment]
This is the script I wrote to interact with this package in O365 https://github.com/tonybaloney/st2-ucwa/blob/master/service/__main__.py

**Comment by toyg** [comment]
Uhm, I'll have to check with our sysadmins what their setup is, I just assumed it was all o365 but I guess you never know. Will get back with the answer.
